[workspace]
authors = ["Samuel Proulx <email@gmail.com>"]
channels = ["conda-forge"]
name = "tabby"
platforms = ["osx-64", "osx-arm64"]
version = "0.1.0"
preview = ["pixi-build"]

[tasks]
test = "pytest"
ui = "streamlit run tools/tabby-ui.py"
install-dev = "pip install -e ."

[dependencies]
tabby = {path = "."}
python = "3.14.*"
numpy = ">=2.3.5,<3"
pytest = ">=9.0.1,<10"
streamlit = ">=1.52.0,<2"
lark = ">=1.3.1,<2"

[package] 
name = "tabby"
version = "0.1.0"

[package.build] 
backend = { name = "pixi-build-python", version = "*" }

# [pypi-dependencies]
# dearpygui = ">=2.1.1, <3"

[tool.pytest.ini_options]
pythonpaths = ["tabby"]

# [tool.pixi.activation]
# scripts = ["pip install -e ."]

# [tool.setuptools.packages.find]
# where = ["."]
# exclude = ["tests*", "tools*"]
